= Meveo - User guide
:nofooter:
:source-highlighter: pygments

[[scripts]]
== Scripts
In Meveo, you can create Java and Javascript scripts. The code of these scripts are stored in the link:<<git>[Meveo git repository]. You can either create them from the user interface under `/pages/admin/storages/scriptInstances/scriptInstances.jsf` or using the REST Api.

A script can be executed from the REST Api using the default endpoint, by a Notification, a Job or an Endpoint.

To ease the communication with other components of Meveo, the user can define named inputs and outputs.

=== Java scripts
All java scripts should be classes that implements the org.meveo.script.ScriptInterface interface. The code of the script is deduced from full name (package name + class name) of the java class.

The parameters can either be taken from the map or be defined through setters. The parameters taken from setters will automatically be added to the list of user defined inputs.

The output can either be added to the map (which is read after the script execution) or defined in a getter.The outputs taken from getters will automatically be added to the list of user defined outputs.

[source,java]
----
package org.meveo.test;

import org.meveo.service.script.Script;
import java.util.Map; 
import org.meveo.admin.exception.BusinessException; 

public class TestSetterAndGetters extends Script { 

    private String field1;

    @Override
    public void execute(Map<String, Object> methodContext) throws BusinessException { 
        String fieldFromMap = methodContext.get("fieldFromMap");
        methodContext.put("output2", "output2");
    }

    /**
    * @param fieldValue Value of the field.
    * Just a test.
    */
    public void setField1(String fieldValue){
        this.field1 = fieldValue;
    }

    /**
    * @return The field previously set
    */
    public String getOutput1(){
        return this.field1 + "increased";
    }
}
----

=== Javascript scripts
The javascript scripts should just be simple scripts that will be evaluated in a java context by the GraalJS library.

The parameters are injected as variables in the script context, so we can access them directly. We can also access them using the `methodContext` object.

The outputs of the script must be added in the `methodContext` map.

[source,javascipt]
----
var inputA = methodContext.get('input'); 
methodContext.put('result', inputA * 2); 
var declaredVar = input * 3;
methodContext.put('result2', declaredVar);
----

[[git]]
== Git

[[git_server]]
=== Git server

You can access the git server like in any other git hosting provider. The remote origin will be accessible at `\https://{host}(:{port})/{context-root}/git/{repository-code}`.

You must authenticate using your Meveo login / password

[[git_repository]]
=== Git repository
A git repository entity reflect a git repository hosted by the Meveo instance. It is defined by a code, a description, a optional remote origin (with optional username and password), reading roles and writing roles. You can access the mangament page at `/pages/admin/storages/repositories/gitRepositories.jsf`.

==== Definition
===== Remote origin
When a git repository has a remote origin, the user can push / pull to / from the remote origin. Default credentials can be defined, but we can also specify them at execution of the action.

===== Reading roles
If reading roles are provided, only user with one of these roles will be able to pull and clone the concerned repository.

===== Writing roles
If writing roles are provided, only user with one of these roles will be able to push to the concerned repository.

==== Operations
===== Commit [API]
When committing a repository, you should provide a commit message and a pattern of the commited files (can be a regex). This operation is only available from API at the moment.

===== Push & Pull
When pushing or pulling a repository, you can specify credentials different from the default credentials. The Meveo instance will behave in the same way when he receives commits from a pull as when he receives a commit from a git client.

===== Import a repository
A zip file can be imported from the file system. If the repository already exist, it will be overriden. This operation is only available for repositories that have no remote origin.

===== Export a repository
The content of a repository can be exported as a zip file. The branch to export can be specified, default branch will be the current branch of the repository.

===== Managing branches [API]
We can checkout, create and delete branches of a git repository. This operation is only available from API at the moment

[[git_how_to]]
=== How to use Git in Meveo ?

Currently, the ontology elements and the scripts are stored in a dedicated git repository hosted by the running Meveo instance, called "Meveo" repository and accessible at `\https://{host}(:{port})/{context-root}/git/Meveo`.

[[git_script]]
==== Scripts
If you clone the Meveo repository, then make some changes to a script, and finally push it, the concerned script will be re-compiled by Meveo and updated. If you create or delete scripts, the action will be reflected on the Meveo instance.

[[git_onto]]
==== Ontology
The ontology elements are serialized under an extended JSON Schema specification. The same rules than for script applies, so if you create, modify or delete a json file, it will be reflected on the Meveo instance you pushed to.

[[git_endpoint]]
==== Endpoints
When updating, creating, or deleting an endpoint, a javascript file will be created. This file contains a default function exported that make a fetch call to the corresponding endpoint. It takes into account the method (GET / POST), the path parameters and the body / query parameters. The return value of this function is a Response object that must be handled.

[[sql_configuration]]
== SQL Configuration
are
SQL Configuration is introduced in version 6.6.0. The idea is to have an option to store different studies on different database locations. For example, study a is stored on data source a while study b is on data source b. By default, the MEVEO manage connection is still available and save as the "default" SqlConfiguration and linked to a "default" repository stored in a database. Unchanged, this is still where the CETs are saved.

[[sql_connection_provider]]
=== SQL Connection Provider

The default repository and SQL configuration are checked on the application start and created if they don't exist yet in the database. The code for this feature is in class _SQLConnectionProvider_. This class also contains the methods to open a new SQL connection with a given SQL configuration. See _SQLConnectionProvider.getSession(SQLConfiguration)_.

[source,ruby]
----
package org.meveo.persistence.sql;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import javax.annotation.PostConstruct;
import javax.ejb.ConcurrencyManagement;
import javax.ejb.ConcurrencyManagementType;
import javax.ejb.Singleton;
import javax.ejb.Startup;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.inject.Provider;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceUnit;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.meveo.commons.utils.ParamBean;
import org.meveo.commons.utils.StringUtils;
import org.meveo.event.qualifier.Updated;
import org.meveo.jpa.EntityManagerWrapper;
import org.meveo.jpa.MeveoJpa;
import org.meveo.model.sql.SqlConfiguration;
import org.slf4j.Logger;

/**
 * @author Edward P. Legaspi | czetsuya@gmail.com
 * @version 6.6.0
 * @since 6.6.0
 */
@Startup
@Singleton
@ConcurrencyManagement(ConcurrencyManagementType.BEAN)
public class SQLConnectionProvider {

	@Inject
	@MeveoJpa
	private Provider<EntityManagerWrapper> emWrapperProvider;
	
    @PersistenceUnit(unitName = "MeveoAdmin")
    private EntityManagerFactory emf;

	@Inject
	private Logger log;

	private String driverClass;
	private String url;
	private String username;
	private String password;
	private String dialect;

	private SqlConfiguration defaultSqlConfiguration = new SqlConfiguration();
	private static final Map<String, SqlConfiguration> configurationMap = new ConcurrentHashMap<>();
	private static final Map<String, SessionFactory> SESSION_FACTORY_MAP = new ConcurrentHashMap<>();

	@PostConstruct
	public void loadConfig() {

		driverClass = ParamBean.getInstance().getProperty("sql.driverClass", "org.postgresql.Driver");
		url = ParamBean.getInstance().getProperty("sql.url", "jdbc:postgresql://localhost/meveo");
		username = ParamBean.getInstance().getProperty("sql.username", "meveo");
		password = ParamBean.getInstance().getProperty("sql.password", "meveo");
		dialect = ParamBean.getInstance().getProperty("sql.dialect", "org.hibernate.dialect.PostgreSQLDialect");

		defaultSqlConfiguration.setCode("default");
		defaultSqlConfiguration.setDriverClass(driverClass);
		defaultSqlConfiguration.setUrl(url);
		defaultSqlConfiguration.setUsername(username);
		defaultSqlConfiguration.setPassword(password);
		defaultSqlConfiguration.setDialect(dialect);
	}

	public SqlConfiguration getSqlConfiguration(String sqlConfigurationCode) {

		SqlConfiguration sqlConfiguration = defaultSqlConfiguration;
		if (StringUtils.isNotBlank(sqlConfigurationCode)) {
			try {
				sqlConfiguration = configurationMap.computeIfAbsent(sqlConfigurationCode, this::findByCode);

			} catch (NoResultException e) {
				log.warn("Unknown SQL repository {}, using default configuration", sqlConfigurationCode);
			}
		}

		return sqlConfiguration;
	}

	public org.hibernate.Session getSession(String sqlConfigurationCode) {

		SqlConfiguration sqlConfiguration = getSqlConfiguration(sqlConfigurationCode);

		try {
			SessionFactory sessionFactory = SESSION_FACTORY_MAP.computeIfAbsent(sqlConfigurationCode, this::buildSessionFactory);
			synchronized (this) {
				return sessionFactory.openSession();
			}

		} catch (Exception e) {
			log.warn("Can't connect to sql configuration with code={}, url={}, error={}", sqlConfigurationCode, sqlConfiguration.getUrl(), e.getCause());
			return null;
		}
	}

	public org.hibernate.Session testSession(SqlConfiguration sqlConfiguration) {

		try {
			SessionFactory sessionFactory = buildSessionFactory(sqlConfiguration);
			synchronized (this) {
				return sessionFactory.openSession();
			}

		} catch (Exception e) {
			log.warn("Can't connect to sql configuration with code={}, url={}, error={}", sqlConfiguration.getCode(), sqlConfiguration.getUrl(), e.getCause());
			return null;
		}
	}

	public synchronized SessionFactory buildSessionFactory(String sqlConfigurationCode) {

		SqlConfiguration sqlConfiguration = getSqlConfiguration(sqlConfigurationCode);

		return buildSessionFactory(sqlConfiguration);
	}

	public synchronized SessionFactory buildSessionFactory(SqlConfiguration sqlConfiguration) {
		// Return the SessionFactory initialized by wildfly in case of using default configuration
		if(sqlConfiguration.getCode().equals("default")) {
			return (SessionFactory) emf;
			
		} else {
			Configuration config = new Configuration();
			config.setProperty("hibernate.connection.driver_class", sqlConfiguration.getDriverClass());
			config.setProperty("hibernate.connection.url", sqlConfiguration.getUrl());
			config.setProperty("hibernate.connection.username", sqlConfiguration.getUsername());
			config.setProperty("hibernate.connection.password", sqlConfiguration.getPassword());
			if (StringUtils.isNotBlank(sqlConfiguration.getDialect())) {
				config.setProperty("hibernate.dialect", sqlConfiguration.getDialect());
			}

			return config.buildSessionFactory();
		}
	}

	public SqlConfiguration findByCode(String code) {

		EntityManager entityManager = emWrapperProvider.get().getEntityManager();
		CriteriaBuilder cb = entityManager.getCriteriaBuilder();
		CriteriaQuery<SqlConfiguration> query = cb.createQuery(SqlConfiguration.class);
		Root<SqlConfiguration> root = query.from(SqlConfiguration.class);
		query.select(root);
		query.where(cb.equal(root.get("code"), code));

		return entityManager.createQuery(query).getSingleResult();
	}

	public void onSqlConnectionUpdated(@Observes @Updated SqlConfiguration entity) {

		configurationMap.put(entity.getCode(), entity);

		SessionFactory oldSessionFactory = SESSION_FACTORY_MAP.get(entity.getCode());
		if (oldSessionFactory != null && oldSessionFactory.isOpen()) {
			oldSessionFactory.close();
		}

		// SESSION_FACTORY_MAP.put(entity.getCode(),
		// buildSessionFactory(entity.getCode()));
		// so that the session factory will get reinitialize the next time a new session
		// is requested
		SESSION_FACTORY_MAP.remove(entity.getCode());
	}

	public String getDriverClass() {
		return driverClass;
	}

	public void setDriverClass(String driverClass) {
		this.driverClass = driverClass;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDialect() {
		return dialect;
	}

	public void setDialect(String dialect) {
		this.dialect = dialect;
	}

	public SqlConfiguration getDefaultSqlConfiguration() {
		return defaultSqlConfiguration;
	}

	public void setDefaultSqlConfiguration(SqlConfiguration defaultSqlConfiguration) {
		this.defaultSqlConfiguration = defaultSqlConfiguration;
	}
}
----

[[sql_configuration_repository]]
=== Repository

A repository is a storage object that holds the connection setting for the different data sources. Currently, there are three supported data sources SQL, Neo4j and Binary or files.

The data on two or more SQL data sources are not merged, that is why a repository filter is provided on both API and GUI.

[[sql_configuration_table]]
=== SQL Configuration Table

Here are the fields of the table SqlConfiguration:

.SQL Configuration Table 
|===
|Field |Description
|String driverClass
|The class used to load this data source, the appropriate jar must be in the classpath. By default, PostgreSQL and Neo4j are already loaded.

|String url
|This is the URL of this data source. For example jdbc:postgresql://localhost:5432/meveo.

|String username
|The data source's username.

|String password
|The data source's password.

|String dialect
|The data source's dialect. Hibernate uses dialect configuration to know which database you are using so that it can switch to the database-specific SQL generator code whenever necessary.

|boolean initialized
|True if this data source has already been initialized.

|===

[[sql_configuration_gui_api]]
=== GUI & API

In the GUI, A new CRUD page is created for SQL Configuration. It is available under Administration / Storages / SQL Configuration menu.

An API endpoint is created for SQL Configuration CRUD operations accessible at `/api/rest/sql/configurations`.  Available operations are CREATE, UPDATE, DELETE, LIST, FIND.

Here is an example request for creating an SQL Configuration:

 Endpoint: /api/rest/sql/configurations
 Method: POST

[source,json]
----
{
    "code": "POSTGRESQL2",
    "description": "PostgreSQL Database",
    "driverClass": "org.postgresql.Driver",
    "url": "jdbc:postgresql://localhost/meveo",
    "username": "meveo",
    "password": "meveo",
    "dialect": "org.hibernate.dialect.PostgreSQLDialect"
}
----