
[[scripts]]
=== Scripts
In Meveo, you can create Java and Javascript scripts. The code of these scripts are stored in the link:<<git>[Meveo git repository]. You can either create them from the user interface under `/pages/admin/storages/scriptInstances/scriptInstances.jsf` or using the REST Api.

A script can be executed from the REST Api using the default endpoint, by a Notification, a Job or an Endpoint.

To ease the communication with other components of Meveo, the user can define named inputs and outputs.

==== Java scripts
All java scripts should be classes that implements the org.meveo.script.ScriptInterface interface. The code of the script is deduced from full name (package name + class name) of the java class.

The parameters can either be taken from the map or be defined through setters. The parameters taken from setters will automatically be added to the list of user defined inputs.

The output can either be added to the map (which is read after the script execution) or defined in a getter.The outputs taken from getters will automatically be added to the list of user defined outputs.

[source,java]
----
package org.meveo.test;

import org.meveo.service.script.Script;
import java.util.Map; 
import org.meveo.admin.exception.BusinessException; 

public class TestSetterAndGetters extends Script { 

    private String field1;

    @Override
    public void execute(Map<String, Object> methodContext) throws BusinessException { 
        String fieldFromMap = methodContext.get("fieldFromMap");
        methodContext.put("output2", "output2");
    }

    /**
    * @param fieldValue Value of the field.
    * Just a test.
    */
    public void setField1(String fieldValue){
        this.field1 = fieldValue;
    }

    /**
    * @return The field previously set
    */
    public String getOutput1(){
        return this.field1 + "increased";
    }
}
----

==== Javascript scripts
The javascript scripts should just be simple scripts that will be evaluated in a java context by the GraalJS library.

The parameters are injected as variables in the script context, so we can access them directly. We can also access them using the `methodContext` object.

The outputs of the script must be added in the `methodContext` map.

[source,javascipt]
----
var inputA = methodContext.get('input'); 
methodContext.put('result', inputA * 2); 
var declaredVar = input * 3;
methodContext.put('result2', declaredVar);
----