
==== Option 1 - Installing as Standalone Serversw.

===== Keycloak

. Download and extract Keycloak to your PC. Let's call the folder where you extracted the files KEYCLOAK_HOME.
. Open the file KEYCLOAK_HOME/standalone/configuration/standalone.xml.
. Find this line <socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}"> and replace the port-offset:0 with port-offset:1. This means 1 will be added to all default ports. Making the oauth url available at port 8081.
. To start the server run KEYCLOAK_HOME\bin\standalone.exe.
. Try accessing http://localhost:8081 from your web browser.
. Create an initial admin user by entering a username and password and proceed to login. You should be able to arrive at the Keycloak admin interface.
. In the left panel, hover on Master and click Add Realm.
. In the right panel, click Select a file and choose meveo-realm.json file. link:meveo-realm.json[Meveo Realm]
. Click create. The Meveo realm should be created and it should now be the selected realm.
. Back in the left panel, click Import / Select a file and select meveo-users-0.json file. link:meveo-users-0.json[Meveo Users]
. Hit import.

To check if meveo realm is correctly configured:

 - Click the Users menu and you should see 9 users.
 - Click the Clients menu and you should see meveo-web.

In the eclipse section, we will discuss how we can integrate Keycloak so we can start it from there.

===== Wildfly

. Download the PostgreSQL driver.
. Download and extract Wildfly into your PC. Let's call the folder where you extracted the files WILDFLY_HOME.
. Inside WILDFLY_HOME/modules folder create this folder hierarchy org/postgresql/main.
. Navigate to this folder.
. Copy and paste the PostgreSQL driver (postgresql-42.2.4.jar) here.
. Create a new file module.xml with the content below.

[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>
<module xmlns="urn:jboss:module:1.1" name="org.postgresql">
    <resources>
        <resource-root path="postgresql-42.2.4.jar"/>
    </resources>

    <dependencies>
        <module name="javax.api"/>
        <module name="javax.transaction.api"/>
    </dependencies>
</module>
----

====== Add the Keycloak Adapter to Wildfly

. Download the Keycloak Adapter with the same version as the downloaded Keycloak Server.
. Copy the downloaded file into WILDFLY_HOME and extract.
. Run command prompt and navigate to WILDFLY_HOME\bin folder.
. Open WILDFLY_HOME\bin\adapter-install-offline.cli and change the standalone to standalone-full.
. Execute: jboss-cli.bat --file=adapter-install-offline.cli.
. A success message should be shown.

====== Add System Properties

At the end of extensions tag add the following properties.

[source,xml]
----
<system-properties>
    <property name="jboss.as.management.blocking.timeout" value="900"/>
    <property name="meveo.instance.name" value="demo"/>
    <property name="java.net.preferIPv4Stack" value="true"/>
    <property name="meveo.keycloak.url" value="http://localhost:8081/auth"/>
    <property name="meveo.keycloak.secret" value="afe07e5a-68cb-4fb0-8b75-5b6053b07dc3"/>
    <property name="meveo.keycloak.realm" value="meveo"/>
    <property name="meveo.keycloak.client" value="meveo-web"/>
    <property name="meveo.admin.server.name" value="localhost"/>
    <property name="meveo.admin.port.number" value="5432"/>
    <property name="meveo.admin.database.name" value="meveo"/>
    <property name="meveo.admin.database.driver" value="postgresql"/>
    <property name="meveo.admin.database.username" value="postgres"/>
    <property name="meveo.admin.database.password" value="<your-postgresql-admin-password>"/>
    <property name="jboss.tx.node.id" value="meveo-default"/>
    <property name="meveo.keycloak.fixed-hostname" value="localhost"/>
    <property name="resteasy.preferJacksonOverJsonB" value="true"/>
</system-properties>
----

*Note that we are using the postgres admin account here.

====== Add a Datasource

. Open the file WILDFLY_HOME\standalone\configuration\standalone.xml.
. Search for "subsystem xmlns="urn:jboss:domain:datasources".
. Add the following datasource configuration.
[source,xml]
----
<xa-datasource jndi-name="java:jboss/datasources/MeveoAdminDatasource" pool-name="meveo" enabled="true" use-java-context="true" use-ccm="false">
    <xa-datasource-property name="ServerName">
        ${meveo.admin.server.name}
    </xa-datasource-property>
    <xa-datasource-property name="PortNumber">
        5432
    </xa-datasource-property>
    <xa-datasource-property name="DatabaseName">
        meveo
    </xa-datasource-property>
    <driver>postgresql</driver>
    <xa-pool>
        <min-pool-size>10</min-pool-size>
        <max-pool-size>200</max-pool-size>
        <prefill>false</prefill>
        <use-strict-min>false</use-strict-min>
        <flush-strategy>FailingConnectionOnly</flush-strategy>
    </xa-pool>
    <security>
        <user-name>${meveo.admin.database.username:meveo}</user-name>
        <password>${meveo.admin.database.password:meveo}</password>
    </security>
    <validation>
        <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"/>
        <validate-on-match>true</validate-on-match>
        <background-validation>false</background-validation>
        <use-fast-fail>true</use-fast-fail>
        <exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"/>
    </validation>
    <timeout>
        <blocking-timeout-millis>60000</blocking-timeout-millis>
        <idle-timeout-minutes>15</idle-timeout-minutes>
    </timeout>
    <statement>
        <share-prepared-statements>true</share-prepared-statements>
    </statement>
</xa-datasource>
----

Add the PostgreSQL driver as well in the drivers section:

[source,xml]
----
<driver name="postgresql" module="org.postgresql">
    <driver-class>org.postgresql.Driver</driver-class>
    <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>
</driver>
----

====== Add Infinispan Cache

Search for "subsystem xmlns="urn:jboss:domain:infinispan" and add the cache container below.

[source,xml]
----
<cache-container name="meveo">
    <local-cache name="meveo-multiTenant-cache"/>
    <local-cache name="meveo-price-plan"/>
    <local-cache name="meveo-usage-charge-template-cache"/>
    <local-cache name="meveo-charge-instance-cache"/>
    <local-cache name="meveo-counter-cache"/>
    <local-cache name="meveo-edr-cache">
        <object-memory size="100000"/>
    </local-cache>
    <local-cache name="meveo-access-cache"/>
    <local-cache name="meveo-cft-cache"/>
    <local-cache name="meveo-cet-cache"/>
    <local-cache name="meveo-notification-cache"/>
    <local-cache name="meveo-balance"/>
    <local-cache name="meveo-reservedBalance"/>
    <local-cache name="meveo-usageChargeInstanceWallet"/>
    <local-cache name="meveo-running-jobs"/>
    <local-cache name="unique-crt">
        <expiration interval="300000" lifespan="300000"/>
    </local-cache>
    <local-cache name="endpoints-results">
        <expiration interval="604800000" lifespan="604800000"/>
    </local-cache>
    <local-cache name="meveo-es-index-cache"/>
    <local-cache name="meveo-crt-cache"/>
    <local-cache name="meveo-rows-page-cache"/>
</cache-container>
----

====== Download Meveo Properties

. Download this file link:meveo-admin.properties[Meveo properties file].
. Make sure to make the necessary changes depending on your local configuration. See keys like meveo.log.file, binary.storage.path and providers.rootDir.
. Copy this file into WILDFLY_HOME\standalone\configuration.

====== Create a Wildfly Admin User

. Open a command prompt.
. Navigate to WILDFLY_HOME\bin.
. Run add-user.bat.
.. Select management User
. Enter your desired user account.
. An "admin" account already exists, so you must update it instead.
. Enter any String for group.

====== Login to Wildfly Server

. Open your favorite browser.
. Enter the url localhost:8080.
. Click Administration Console.
. Login using your newly created account.

A completely configured file is available for reference link:standalone.xml[here].